### ISSUE TITLE
Two small bugs

### ISSUE THREAD

**Issue by monnerat** [ej52/alpine-nginx-php#2]
Hi Elton,
First, thank you for your image.

I found 2 small bugs in it:
a) Not able to upload files > 1024 bytes.
  In /etc/php/php.ini, the line

upload_max_filesize = 1024MB

should be

upload_max_filesize = 1024M

MB is not properly understood by PHP.

b) The /var/lib/php7/sessions directory should be writable for www-data.

Regards,
Patrick

**Comment by ej52** [comment]
@monnerat Thanks for pointing these out, have fixed them in https://github.com/ej52/alpine-nginx-php/commit/2308c97a812ac8017c8cc756ce2ef9b6d030784b and https://github.com/ej52/alpine-nginx-php/commit/2a031cf8043ae007eb2a4871f1bcd0c1155ad50a ;)
