### ISSUE TITLE
Invalid default timezone

### ISSUE THREAD

**Issue by shaxbee** [ej52/alpine-nginx-php#3]
Usage of date() family of functions triggers `NOTICE: PHP message: PHP Warning:  date(): Invalid date.timezone value 'Africa/London'` warning, can it be sent to some sensible value by default, eg. UTC?

**Comment by ej52** [comment]
@shaxbee Thanks for pointing this issue out, has been fixed in https://github.com/ej52/alpine-nginx-php/commit/7c0c40c4bc2bb1eaa4a889790421b700e048588f

**Comment by ej52** [comment]
fix in https://github.com/ej52/alpine-nginx-php/commit/7c0c40c4bc2bb1eaa4a889790421b700e048588f
